### ISSUE TITLE
problem getting output

### ISSUE THREAD

**Issue by sophienguyen01** [Genome-Bioinformatics-RadboudUMC/DeNovoCNN#10]
Hi,

I use docker to run DenovoCNN using the command in the README file. 
The workload seems to run successful but I cannot find the output file 'predictions.csv` in my designated output folder. 

I wonder if anyone ran into the same problem like me or not?

**Comment by ty-hei** [comment]
I also meet this problem, have you slove it?

**Comment by sophienguyen01** [comment]
I think it's the problem with the running environment. It fails on my local computer but works if I run on an AWS EC2 instance.

**Comment by ty-hei** [comment]
I use the command
```bash 
bash apply_denovocnn.sh\
    --workdir=/data/userah/tmp/DenovoCNN_test \
    --child-vcf=/data/userah/tmp/trio_WES/variants/CHILD.vcf.gz \
    --father-vcf=/data/userah/tmp/trio_WES/variants/FU0.vcf.gz \
    --mother-vcf=/data/userah/tmp/trio_WES/variants/MU0.vcf.gz \
    --child-bam=/data/userah/tmp/trio_WES/alignments/CHILD.bwa.markdup.rg.bam \
    --father-bam=/data/userah/tmp/trio_WES/alignments/FU0.bwa.markdup.rg.bam \
    --mother-bam=/data/userah/tmp/trio_WES/alignments/MU0.bwa.markdup.rg.bam \
    --snp-model=/data/userah/my_bin/DeNovoCNN-main/models/snp \
    --in-model=/data/userah/my_bin/DeNovoCNN-main/models/ins \
    --del-model=/data/userah/my_bin/DeNovoCNN-main/models/del \
    --genome=/data/userah/my_ref/hg38.fa \
    --output=predictions.csv
```
Here is the output,
```
Traceback (most recent call last):
  File "/data/userah/my_bin/DeNovoCNN-main/main.py", line 81, in <module>
    apply_models_on_trio(
  File "/data/userah/my_bin/DeNovoCNN-main/denovonet/dataset.py", line 378, in apply_models_on_trio
    dataset = Dataset(dataset=dataset, convert_to_inner_format=convert_to_inner_format)
  File "/data/userah/my_bin/DeNovoCNN-main/denovonet/dataset.py", line 48, in __init__
    self.standartize_variants()
  File "/data/userah/my_bin/DeNovoCNN-main/denovonet/dataset.py", line 58, in standartize_variants
    self.dataset['Variant type'] = self.dataset.apply(get_variant_class, axis=1)
  File "/data/userah/mambaforge/envs/tensorflow_env/lib/python3.8/site-packages/pandas/core/frame.py", line 3040, in __setitem__
    self._set_item(key, value)
  File "/data/userah/mambaforge/envs/tensorflow_env/lib/python3.8/site-packages/pandas/core/frame.py", line 3117, in _set_item
    NDFrame._set_item(self, key, value)
  File "/data/userah/mambaforge/envs/tensorflow_env/lib/python3.8/site-packages/pandas/core/generic.py", line 3577, in _set_item
    self._mgr.insert(len(self._info_axis), key, value)
  File "/data/userah/mambaforge/envs/tensorflow_env/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1189, in insert
    block = make_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "/data/userah/mambaforge/envs/tensorflow_env/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 2722, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/data/userah/mambaforge/envs/tensorflow_env/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 2378, in __init__
    super().__init__(values, ndim=ndim, placement=placement)
  File "/data/userah/mambaforge/envs/tensorflow_env/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 130, in __init__
    raise ValueError(
ValueError: Wrong number of items passed 11, placement implies 1
DenovoCNN finished.
Output in:
/data/userah/tmp/DenovoCNN_test/predictions.csv
```

It seems that something is wrong with the Dataframe of pandas, And the file `predictions.csv` have not been created. 

I have no idea about how to solve this error.

**Comment by gelana** [comment]
Hi @heihaheihaha,

I'm sorry to hear that you're experiencing issues with the tool.

From the error message provided, it's not entirely clear what's causing the problem. If you're running the tool with the specified command, you should find a file named `variants_list.txt` in the `/data/userah/tmp/DenovoCNN_test` folder.

Could you please share a few lines from this file? This will help me better understand the issue and attempt to reproduce it.

Thank you!

**Comment by ty-hei** [comment]
@gelana The problem is solved, it is due to the small testing data in my workflow. The `variants_list.txt` is **empty**, that is why I could not find `predictions.csv`. Timely checking input files and reporting errors may be a good idea.
Thank you for your help~

**Comment by style211** [comment]
I ran the WGS data for the family tree using your code, but I didn't see the final file generated either. Could you tell me what your final command was? Here's what mine looked like:
bash apply_denovocnn.sh
--workdir=/media/zengyiheng/3E7C98237C97D3CD/NF1/33679wgs/output
--child-vcf=/media/zengyiheng/3E7C98237C97D3CD/NF1/33679wgs/input/33679wgs.vcf
--father-vcf=/media/zengyiheng/3E7C98237C97D3CD/NF1/33679wgs/input/33682wgs.vcf
--mother-vcf=/media/zengyiheng/3E7C98237C97D3CD/NF1/33679wgs/input/33681wgs.vcf
--child-bam=/media/zengyiheng/3E7C98237C97D3CD/NF1/33679wgs/input/33679wgs.hg19.sorted.markdup.bqsr.bam
--father-bam=/media/zengyiheng/3E7C98237C97D3CD/NF1/33679wgs/input/33682wgs.hg19.sorted.markdup.bqsr.bam
--mother-bam=/media/zengyiheng/3E7C98237C97D3CD/NF1/33679wgs/input/33681wgs.hg19.sorted.markdup.bqsr.bam
--snp-model=/media/zengyiheng/3E7C98237C97D3CD/DeNovoCNN-main/models/snp
--in-model=/media/zengyiheng/3E7C98237C97D3CD/DeNovoCNN-main/models/ins
--del-model=/media/zengyiheng/3E7C98237C97D3CD/DeNovoCNN-main/models/del
--genome=/media/zengyiheng/3E7C98237C97D3CD/NF1/33679wgs/input/hg19_22XY.fasta
--output=predictions.csv
The error message is：
Variants list created in: /media/zengyiheng/3E7C98237C97D3CD/NF1/33679wgs/output/variants_list.txt
Preprocessing step finished.
Running DenovoCNN...
/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:513: FutureWarning: In the future np.object will be defined as the corresponding NumPy scalar.
np.object,
Traceback (most recent call last):
File "/media/zengyiheng/Expansion/denovocnn/DeNovoCNN-main/main.py", line 24, in
from denovonet.dataset import apply_models_on_trio
File "/media/zengyiheng/Expansion/denovocnn/DeNovoCNN-main/denovonet/dataset.py", line 33, in
import tensorflow as tf
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/init.py", line 41, in
from tensorflow.python.tools import module_util as _module_util
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/init.py", line 45, in
from tensorflow.python import data
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/data/init.py", line 25, in
from tensorflow.python.data import experimental
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/data/experimental/init.py", line 96, in
from tensorflow.python.data.experimental import service
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/data/experimental/service/init.py", line 21, in
from tensorflow.python.data.experimental.ops.data_service_ops import distribute
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 25, in
from tensorflow.python.data.experimental.ops import compression_ops
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 20, in
from tensorflow.python.data.util import structure
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py", line 26, in
from tensorflow.python.data.util import nest
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 41, in
from tensorflow.python.framework import sparse_tensor as _sparse_tensor
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/framework/sparse_tensor.py", line 29, in
from tensorflow.python.framework import constant_op
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 29, in
from tensorflow.python.eager import execute
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 27, in
from tensorflow.python.framework import dtypes
File "/home/zengyiheng/crk/miniconda/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py", line 513, in
np.object,
File "/home/zengyiheng/.local/lib/python3.8/site-packages/numpy/init.py", line 305, in getattr
raise AttributeError(former_attrs[attr])
AttributeError: module 'numpy' has no attribute 'object'.
np.object was a deprecated alias for the builtin object. To avoid this error in existing code, use object by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
DenovoCNN finished.
Output in:
/media/zengyiheng/3E7C98237C97D3CD/NF1/33679wgs/output/predictions.csv
