### ISSUE TITLE
Missing module 'denovonet'

### ISSUE THREAD

**Issue by AleksG98** [Genome-Bioinformatics-RadboudUMC/DeNovoCNN#14]
Hi!
I am trying to use this tool for calling denovo variants in WES data. However, I seem to have an issue with a missing module. 
Here is the code and the error message I get:

 ./apply_denovocnn.sh -w="/mnt/d/COS/CombineGVCF/trios_denovo/DeNovoCNN/trial2" -cv="/mnt/d/COS/CombineGVCF/trios_denovo/sample2.vcf" -fv="/mnt/d/COS/CombineGVCF/trios_denovo/sample3.vcf" -mv="/mnt/d/COS/CombineGVCF/trios_denovo/sample1.vcf" -cb="/mnt/d/COS/CombineGVCF/trios_denovo/DeNovoCNN/aligned_sample2.bam" -fb="/mnt/d/COS/CombineGVCF/trios_denovo/DeNovoCNN/aligned_sample3.bam" -mb="/mnt/d/COS/CombineGVCF/trios_denovo/DeNovoCNN/aligned_sample1.bam" -sm="/mnt/d/COS/CombineGVCF/trios_denovo/DeNovoCNN/saved_model_snps.pb" -im="/mnt/d/COS/CombineGVCF/trios_denovo/DeNovoCNN/saved_model_ins.pb" -dm="/mnt/d/COS/CombineGVCF/trios_denovo/DeNovoCNN/saved_model_del.pb" -g="/mnt/c/Users/Aleksandra/Desktop/COS/GRCh38.p14.genome.fa" -o="/mnt/d/COS/CombineGVCF/trios_denovo/DeNovoCNN/predictions_trio1.csv"

Running DenovoCNN...
Traceback (most recent call last):
  File "/mnt/d/COS/CombineGVCF/trios_denovo/DeNovoCNN/main.py", line 24, in <module>
    from denovonet.dataset import apply_models_on_trio
ModuleNotFoundError: No module named 'denovonet'

I can't seem to find this module on the page, so I was wondering if you could help me?
Thank you!

**Comment by gelana** [comment]
Hi @AleksG98 , 
Thanks for using DeNovoCNN! I would recommend using docker or singularity container to simplify the tools usage. Otherwise you can install the module to the tensorflow_env environment by running the following commands:

1. conda activate tensorflow_env
2. cd .../DeNovoCNN
3. pip install -e .

This will install denovonet module into tensorflow_env environment. Hope that helps!

**Comment by poddarharsh15** [comment]
Hi @gelana,

I'm encountering issues with conda despite following the suggestions in the previous comment. Although I can see the 'denovonet' module installed in the 'tensorflow_env' environment, I'm still encountering errors. Could you please provide further advice?

Thank you.
>`./apply_denovocnn.sh \
>   -w=/home/tigem/h.poddar/denovocnn/conda_denovoCNN/DeNovoCNN \
> -cv=/home/tigem/h.poddar/denovocnn/run_denovo/quickstart-testdata/HG002.vcf \
> -fv=/home/tigem/h.poddar/denovocnn/run_denovo/quickstart-testdata/HG003.vcf \
> -mv=/home/tigem/h.poddar/denovocnn/run_denovo/quickstart-testdata/HG004.vcf  \
>  -cb=/home/tigem/h.poddar/denovocnn/run_denovo/quickstart-testdata/HG002.bam \
>  -fb=/home/tigem/h.poddar/denovocnn/run_denovo/quickstart-testdata/HG003.bam \
> -mb=/home/tigem/h.poddar/denovocnn/run_denovo/quickstart-testdata/HG004.bam  \
> -sm=/app/models/snp \
> -im=/app/models/ins \
> -dm=/app/models/del  \
> -g=/home/tigem/h.poddar/denovocnn/run_denovo/quickstart-testdata/GRCh38.primary_assembly.genome.fa \
> -v=/home/tigem/h.poddar/denovocnn/run_denovo/quickstart-testdata/all_variants.txt \
> -o=predictions.csv 
`

> Start preprocessing step...
mkdir: cannot create directory '/home/tigem/h.poddar/denovocnn/conda_denovoCNN/DeNovoCNN': File exists
Preprocessing step finished.
Running DenovoCNN...
Traceback (most recent call last):
  File "/net/192.168.120.240/home/tigem/h.poddar/denovocnn/conda_denovoCNN/main.py", line 24, in <module>
    from denovonet.dataset import apply_models_on_trio
ModuleNotFoundError: No module named 'denovonet'
DenovoCNN finished.
Output in:
/home/tigem/h.poddar/denovocnn/conda_denovoCNN/DeNovoCNN/predictions.csv

**Comment by gelana** [comment]
Hi @poddarharsh15, 

I've never encountered similar issues before. My only thought is that perhaps the environment isn't selected correctly. Could you please double-check that you're launching the denovo caller within the tensorflow_env environment?

**Comment by poddarharsh15** [comment]
Hi @gelana,

Thank you for your response. I identified the issue—I didn't have the module in my directory and I didn't provide the correct path for denovonet. Now it's working fine, and yes, I am running denovoCNN in the tensorflow_env environment.
The process has been running since yesterday. Could you please check if there are any errors?
Thank you.
![Screenshot from 2024-05-07 12-16-07](https://github.com/Genome-Bioinformatics-RadboudUMC/DeNovoCNN/assets/45700858/402050a8-c32d-452f-8eee-4ddbd2cb2639)

> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-06 18:56:44.847048: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2900000000 Hz
2024-05-06 18:56:44.876511: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f983ce11150 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-05-06 18:56:44.885041: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

I am seeing this quote in terminal I am worried something's not right could please have a look at it :))
